apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: nodejs-ec2-production
  title: NodeJS Service with EC2 (Production)
  description: Creates app repo + infra repo with Terraform CI/CD
spec:
  owner: user:guest
  type: service

  parameters:
    - title: Project Info
      required:
        - name
        - owner
      properties:
        name:
          type: string
          title: Service Name
          ui:autofocus: true

        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              - kind: [User, Group]

        instanceType:
          type: string
          title: EC2 Instance Type
          default: t2.micro
          enum:
            - t2.micro
            - t2.small
            - t2.medium

    - title: Choose Location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          description: Where to create the app repository
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:

    # ================= INFRA =================

    - id: fetch-infra
      name: Fetch Infra Template
      action: fetch:template
      input:
        url: https://github.com/0019-KDU/express-service-infra-template
        targetPath: infra
        values:
          project_name: ${{ parameters.name }}
          instance_type: ${{ parameters.instanceType }}
          owner: ${{ parameters.owner }}

    - id: publish-infra
      name: Publish Infra Repo
      action: publish:github
      input:
        sourcePath: infra
        repoUrl: github.com?repo=${{ parameters.name }}-infra&owner=${{ (parameters.repoUrl | parseRepoUrl).owner }}
        description: Terraform infra for ${{ parameters.name }}
        defaultBranch: main

    - id: register-infra
      name: Register Infra
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish-infra'].output.repoContentsUrl }}
        catalogInfoPath: '/resource.yaml'

    # ================= APP =================

    - id: fetch-app
      name: Fetch App Template
      action: fetch:template
      input:
        url: https://github.com/0019-KDU/express-service-template
        targetPath: app
        values:
          name: ${{ parameters.name }}
          owner: ${{ parameters.owner }}

    - id: publish-app
      name: Publish App Repo
      action: publish:github
      input:
        sourcePath: app
        repoUrl: ${{ parameters.repoUrl }}
        description: Express.js app for ${{ parameters.name }}
        defaultBranch: main

    - id: register-app
      name: Register App
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish-app'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: App Repository
        url: ${{ steps['publish-app'].output.remoteUrl }}
      - title: Infra Repository
        url: ${{ steps['publish-infra'].output.remoteUrl }}
      - title: Open in Backstage Catalog
        icon: catalog
        entityRef: ${{ steps['register-app'].output.entityRef }}
