apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: auth-service
  description: Simple authentication service with JWT tokens
  tags:
    - python
    - flask
    - auth
  links:
    - url: https://google.com
      title: Google
      icon: dashboard
      type: website
spec:
  type: service
  lifecycle: experimental
  owner: guests
  providesApis:
    - auth-api

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: auth-api
  description: Verify user authentication status
spec:
  type: openapi
  lifecycle: production
  owner:  guests
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Artist API
      license:
        name: MIT
    servers:
      - url: http://artist.spotify.net/v1
    paths:
      /artists:
        get:
          summary: List all artists
    ...