apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: purchasing
  description: system for managing user purchases
spec:
  owner: ecommerce   
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: shopping-cart
spec:
  dependsOn:
    - component:inventory
  type: website
  lifecycle: production
  owner: user:john
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: inventory
spec:
  type: servcie
  lifecycle: production
  owner: ecommerce
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: ecommerce
spec:
  type: team
  children: []  

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: john
spec:
  memberOf: [ecommerce]  