apiversion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: shooping-app
  description: Handles everything in the ecommerce portion of the business
spec:
  owner: ecommerce
  subdomainOf: audio-domain   
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: purchasing
  description: system for managing user purchases
spec:
  owner: ecommerce   
  domain: shopping-app
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: shopping-cart
spec:
  dependsOn:
    - component:inventory
  type: website
  lifecycle: production
  owner: user:john
  system: purchasing
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: inventory
spec:
  dependsOn:
    - resource:inventory-db
  type: servcie
  lifecycle: production
  owner: ecommerce
  system: purchasing

---
apiVersion: backstage.io/v1alpha1
kind: Resources
metadata:
  name: inventory-db
  description: Stores inventory details
spec:
  type: database
  owner: ecommerce
  system: purchasing
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: ecommerce
spec:
  type: team
  children: []  

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: john
spec:
  memberOf: [ecommerce]  